### PR TITLE
Fix Logger#getMessageLogger deprecation and related cleanup.

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by rhusar** [comment]
for @ehsavoie

**Comment by ehsavoie** [comment]
out of date

**Comment by ehsavoie** [comment]
@rhusar Thanks :)

**Comment by rhusar** [comment]
@ehsavoie I guess now you see why I was asking you "if I open PRs will you merge them?" :-)

**Comment by rhusar** [comment]
Anyway, not completely incorported - opened https://github.com/wildfly-extras/wildfly-ai-feature-pack/pull/37 now

**Pull request closed without merging**
